---
_upgrade_yes_no:
  - "{{ 'Y' if upgrade_set_default | bool else 'n' }}"
  - "{{ 'Y' if upgrade_copy_config | bool else 'n' }}"
  - "{{ 'Y' if upgrade_copy_ssh_keys | bool else 'n' }}"
_upgrade_add_command: >-
  add system image {{ upgrade_image_url }}{{ (' vrf ' ~ upgrade_vrf) if upgrade_vrf else '' }}
