---
ipsec_policy_based_ike_group:
  name: IKE-GROUP
  key_exchange: ikev2
  lifetime: 28800
  dh_group: 14
  encryption: aes256
  hash: sha256
  close_action: start
  dead_peer_detection: {action: restart, interval: 10, timeout: 30}
ipsec_policy_based_esp_group:
  name: ESP-GROUP
  lifetime: 3600
  pfs: dh-group14
  encryption: aes256
  hash: sha256
ipsec_policy_based_default_gateway: ""
ipsec_policy_based_interfaces: []
ipsec_policy_based_options: {}
