---
base_interfaces:
  - {name: eth1.201, addresses: [10.200.201.2/24]}
  - {name: eth1.100, addresses: [203.0.113.2/24]}
ha_vrrp_priority: 200
ha_vrrp_local_addresses: {int: 10.200.201.2, public: 203.0.113.2}
ha_vrrp_conntrack_sync_local_address: 10.200.201.2
