---
- name: IS-IS with MPLS segment routing
  hosts: p_routers
  gather_facts: false
  roles:
    - vyos.blueprints.base # loopback, link addresses and MTU, hostname
    - vyos.blueprints.isis # IS-IS, segment routing, MPLS interfaces
  post_tasks:
    - name: Show rendered commands
      ansible.builtin.debug:
        var: vyos_blueprints_rendered
      when: show_rendered | default(false) | bool
