name: bp-azure
topology:
  kinds:
    vyosnetworks_vyos:
      image: ${VYOS_IMAGE:=vyos:blueprints-ci}
  nodes:
    vyos:
      kind: vyosnetworks_vyos
    # second VyOS standing in for the Azure VNet gateway
    azure:
      kind: vyosnetworks_vyos
    isp:
      kind: linux
      image: alpine:3
      exec:
        [
          "sysctl -w net.ipv4.ip_forward=1",
          "ip addr add 198.51.100.1/24 dev eth1",
          "ip addr add 203.0.113.1/24 dev eth2",
        ]
    onprem:
      kind: linux
      image: alpine:3
      exec:
        [
          "ip addr add 10.10.2.10/24 dev eth1",
          "ip route replace default via 10.10.2.1",
        ]
    vm:
      kind: linux
      image: alpine:3
      exec:
        [
          "ip addr add 10.0.1.10/24 dev eth1",
          "ip route replace default via 10.0.1.1",
        ]
  links:
    - endpoints: ["vyos:eth1", "isp:eth1"]
    - endpoints: ["azure:eth1", "isp:eth2"]
    - endpoints: ["vyos:eth2", "onprem:eth1"]
    - endpoints: ["azure:eth2", "vm:eth1"]
