---
- name: Route-based site-to-site IPsec
  hosts: vpn
  gather_facts: false
  roles:
    - vyos.blueprints.base
    - vyos.blueprints.ipsec_route_based
  post_tasks:
    - name: Show rendered commands
      ansible.builtin.debug:
        var: vyos_blueprints_rendered
      when: show_rendered | default(false) | bool
