---
# The page sets no default route on RIGHT; it needs one to reach LEFT.
ipsec_policy_based_peers:
  - name: LEFT
    psk_name: LEFT
    psk: p4ssw0rd # use ansible-vault for real devices
    authentication_ids: false
    local_address: 192.0.2.130
    remote_address: 198.51.100.14
    connection_type: none
    tunnels:
      - { id: 0, local_prefix: 10.2.21.0/24, remote_prefix: 10.1.11.0/24 }
      - { id: 1, local_prefix: 10.2.22.0/24, remote_prefix: 10.1.11.0/24 }
      - { id: 2, local_prefix: 10.2.21.0/24, remote_prefix: 10.1.12.0/24 }
      - { id: 3, local_prefix: 10.2.22.0/24, remote_prefix: 10.1.12.0/24 }
base_interfaces:
  - name: eth3
    addresses: [192.0.2.130/30]
  - name: eth1.221
    addresses: [10.2.21.1/24]
  - name: eth2.222
    addresses: [10.2.22.1/24]
ipsec_policy_based_default_gateway: 192.0.2.129
