---
galaxy_info:
  author: VyOS maintainers and contributors
  description: Routing policy - access-lists, prefix-lists and route-maps
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions: [all]
  galaxy_tags: [vyos, networking, routing, policy]
dependencies: []
