---
all:
  children:
    vyos:
      hosts:
        r1:
          ansible_host: clab-bp-backup-r1
        r2:
          ansible_host: clab-bp-backup-r2
      vars:
        ansible_network_os: vyos.vyos.vyos
        ansible_connection: ansible.netcommon.network_cli
        ansible_user: admin
        ansible_password: admin
        backup_root: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/backups"
        backup_keep: 2
