---
base_interfaces:
  - name: dum10
    addresses:
      - 10.0.0.3/32
  - name: eth0
    addresses:
      - 172.16.30.1/24
  - name: eth1
    addresses:
      - 172.16.40.1/24
  - name: eth2
    addresses:
      - 172.16.90.1/24
  - name: eth3
    addresses:
      - 172.16.10.1/24
  - name: eth5
    addresses:
      - 172.16.100.1/24
ospf_router_id: 10.0.0.3
ospf_areas:
  - id: "0"
    networks:
      - 0.0.0.0/0
ospf_abr_type: cisco
mpls_ldp_router_id: 10.0.0.3
mpls_ldp_interfaces:
  - eth0
  - eth1
  - eth2
  - eth3
  - eth5
base_hostname: VyOS-P1
