#!/usr/bin/env python3
"""Generate roles/<role>/README.md from roles/<role>/meta/argument_specs.yml.

Run from the collection root after changing a role's argument spec:
    python3 scripts/gen-role-readmes.py          # write the READMEs
    python3 scripts/gen-role-readmes.py --check  # exit 1 if any README is out of date
"""
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
MARK = "<!-- generated by scripts/gen-role-readmes.py from meta/argument_specs.yml; do not edit -->"


def text(value):
    """Argument-spec text (str or list of str) to Markdown."""
    parts = value if isinstance(value, list) else [value or ""]
    out = " ".join(str(p).strip() for p in parts)
    out = re.sub(r"[CIBM]\(([^)]*)\)", lambda m: f"`{m.group(1)}`" if m.group(0)[0] in "CM" else m.group(1), out)
    return out.replace("|", "\\|")


def options_table(options, prefix=""):
    rows = []
    for name, spec in (options or {}).items():
        spec = spec or {}
        default = spec.get("default")
        default = "" if default is None else f"`{yaml.safe_dump(default, default_flow_style=True).strip().removesuffix('...').strip()}`"
        required = "yes" if spec.get("required") else ""
        rows.append(f"| `{prefix}{name}` | {spec.get('type', '')} | {required} | {default} | {text(spec.get('description'))} |")
        if spec.get("options"):
            rows.extend(options_table(spec["options"], prefix=f"{prefix}{name}."))
    return rows


def render(role, specs):
    main = specs.get("main", {})
    lines = [MARK, "", f"# vyos.blueprints.{role}", "", text(main.get("short_description")), ""]
    for para in main.get("description") or []:
        lines += [f"- {text(para)}"]
    lines += ["", "## Usage", "", "```yaml", "- hosts: routers", "  gather_facts: false", "  roles:",
              f"    - vyos.blueprints.{role}", "```", ""]
    for entry, spec in specs.items():
        title = "Variables" if entry == "main" else f"Entry point `{entry}` (`tasks_from: {entry}`)"
        lines += [f"## {title}", ""]
        if entry != "main" and spec.get("description"):
            lines += [text(spec["description"]), ""]
        rows = options_table(spec.get("options"))
        if rows:
            lines += ["| Variable | Type | Required | Default | Description |", "|---|---|---|---|---|", *rows, ""]
        else:
            lines += ["No variables.", ""]
    lines += ["## License", "", "GPL-3.0-or-later", ""]
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    stale = []
    for spec_file in sorted(ROOT.glob("roles/*/meta/argument_specs.yml")):
        role = spec_file.parent.parent.name
        content = render(role, yaml.safe_load(spec_file.read_text())["argument_specs"])
        readme = spec_file.parent.parent / "README.md"
        if readme.exists() and readme.read_text() == content:
            continue
        stale.append(role)
        if not check:
            readme.write_text(content)
    if check and stale:
        print("out of date:", ", ".join(stale), "- run scripts/gen-role-readmes.py")
        return 1
    print(("up to date" if check else f"written: {len(stale)}"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
