---
- name: Management plane
  hosts: routers
  gather_facts: false
  roles:
    - vyos.blueprints.base # interface addressing
    - vyos.blueprints.management # SNMP, traps, syslog, NTP, RADIUS login
  post_tasks:
    - name: Show rendered commands
      ansible.builtin.debug:
        var: vyos_blueprints_rendered
      when: show_rendered | default(false) | bool
