---
- name: OSPF unnumbered with ECMP
  hosts: fabric
  gather_facts: false
  roles:
    - vyos.blueprints.base
    - vyos.blueprints.ospf_unnumbered
  post_tasks:
    - name: Show rendered commands
      ansible.builtin.debug:
        var: vyos_blueprints_rendered
      when: show_rendered | default(false) | bool
