---
all:
  children:
    vyos:
      children:
        gre:
          hosts:
            r1:
              ansible_host: clab-bp-gre-r1
              base_interfaces:
                - { name: eth1, addresses: [198.51.100.1/24] }
              gre_tunnel_interfaces:
                - {
                    name: tun1,
                    source_address: 198.51.100.1,
                    remote: 198.51.100.2,
                    mtu: 1376,
                    adjust_mss: "1336",
                    addresses: [172.16.122.1/30],
                  }
            r2:
              ansible_host: clab-bp-gre-r2
              base_interfaces:
                - { name: eth1, addresses: [198.51.100.2/24] }
              gre_tunnel_interfaces:
                - {
                    name: tun1,
                    source_address: 198.51.100.2,
                    remote: 198.51.100.1,
                    mtu: 1376,
                    adjust_mss: "1336",
                    addresses: [172.16.122.2/30],
                  }
      vars:
        ansible_network_os: vyos.vyos.vyos
        ansible_connection: ansible.netcommon.network_cli
        ansible_user: admin
        ansible_password: admin
